# Pre-commit configuration for Pub-Sub Collaborative Editing Demo
# Security-focused configuration - development tools handled by .githooks

default_language_version:
    python: python3.12
    node: 24.4.1

repos:
    # Security and file validation hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: detect-private-key
          - id: check-added-large-files
            args: [--maxkb=3000]
          - id: check-merge-conflict
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          - id: trailing-whitespace
          - id: end-of-file-fixer

    # Security scanning
    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.5.0
      hooks:
          - id: detect-secrets
            args: ["--baseline", ".secrets.baseline"]
            exclude: |
                (?x)^(
                    .*\.lock$|
                    package-lock\.json$|
                    pnpm-lock\.yaml$
                )$

    # Shell script validation
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck
            args: ["--severity=warning"]
            files: \.sh$

    # Biome linting and formatting
    - repo: https://github.com/biomejs/pre-commit
      rev: v2.1.2
      hooks:
          - id: biome-check
            additional_dependencies: ["@biomejs/biome@2.1.2"]

# CI configuration
ci:
    autofix_prs: true
    autoupdate_schedule: weekly
